# Generated by Django 6.0.2 on 2026-03-10 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('logo_name', models.CharField(help_text='Nom du fichier sans extension (ex: Shori → Teams=Shori.png)', max_length=60)),
                ('color', models.CharField(default='#FFFFFF', help_text='Couleur primaire en hexadécimal (ex: #971C22)', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=120)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='ShoriWebsite.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='ShoriWebsite.team')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['datetime'],
            },
        ),
    ]
